"""empty message

Revision ID: 9918ff66ac46
Revises: 
Create Date: 2022-04-26 14:06:53.871728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9918ff66ac46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Favourites', sa.Column('temp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Favourites', 'temp')
    # ### end Alembic commands ###
